;1、域名组
ruleset=AI,http://192.168.10.2/lists/AI.list
ruleset=苹果,http://192.168.10.2/lists/Apple.list
ruleset=微软,http://192.168.10.2/lists/Microsoft.list
ruleset=谷歌,http://192.168.10.2/lists/Google.list
ruleset=电报,http://192.168.10.2/lists/Telegram.list
ruleset=TikTok,http://192.168.10.2/lists/TikTok.list
ruleset=国外流媒体,http://192.168.10.2/lists/Streaming.list

;2、策略组（域名组 - 节点组）
custom_proxy_group=AI`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=苹果`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=微软`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=谷歌`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=电报`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=TikTok`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT
custom_proxy_group=国外流媒体`select`[]DIRECT`[]美国-自动`[]日本-自动`[]新加坡-自动`[]香港-自动`[]所有-自动`[]其他-自动`[]REJECT

;3、节点组
custom_proxy_group=美国-自动`url-test`(US|United States)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=日本-自动`url-test`(JP|Japan|东京|大阪)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=新加坡-自动`url-test`(SG|Singapore)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=香港-自动`url-test`(HK|Hong Kong)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=所有-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=其他-自动`url-test`(波|柬|斯|尼|也|克|比|尔|立|冰|秘|耳|利|埃|希|斯|孟|芬|阿|愛|澳|英|德|南|意|法|拿|墨|印|越|俄|瑞|智|荷|比|巴|沙|班|泰|德|烏|以|Australia|Konghwaguk)`http://www.gstatic.com/generate_204`60,150

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
